Remove requirement for gssapi/gssapi.h in svc_auth.h
When --disable-gssapi is specified and gssapi.h is not installed on
the build system, making libtirpc fails:

  CC       libtirpc_la-bindresvport.lo
In file included from ../tirpc/rpc/svc_auth.h:44:0,
                 from ../tirpc/rpc/rpc.h:68,
                 from bindresvport.c:46:
../tirpc/rpc/rpcsec_gss.h:38:27: fatal error: gssapi/gssapi.h:
					No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.

Commit d5259e751111 added "#include <rpc/rpcsec_gss.h>" to
<rpc/svc_auth.h> . That tries to include <gssapi/gssapi.h>, which
is missing in this case.

Remove the fields added in SVCAUTH that require including
<rpc/rpcsec_gss.h>. These are not part of the TI-RPC public API as
far as I can tell.

Then "#include <rpc/rpcsec_gss.h>" can be safely removed from
<rpc/svc_auth.h> .

Reported-by: Thorsten Kukuk <kukuk@suse.de>
Fixes: d5259e751111 ('Add header definitions for rpc_gss_*() APIs')
Signed-off-by: Chuck Lever <chuck.lever@oracle.com>
Signed-off-by: Steve Dickson <steved@redhat.com>