"configure --enable-gssapi" should fail if gssapi.h not found
"configure --enable-gssapi" on a system without GSS-API installed
completes normally. Then "make" fails with:

  CC       libtirpc_la-bindresvport.lo
In file included from ../tirpc/rpc/rpc.h:64:0,
                 from bindresvport.c:46:
../tirpc/rpc/auth_gss.h:41:27: fatal error: gssapi/gssapi.h:
					No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
Makefile:604: recipe for target 'libtirpc_la-bindresvport.lo' failed

Since gssapi.h is a requirement when --enable-gssapi is specified,
make ./configure fail if gssapi.h is not installed.

Signed-off-by: Chuck Lever <chuck.lever@oracle.com>
Signed-off-by: Steve Dickson <steved@redhat.com>